spring:
  datasource:
      url: jdbc:mysql://localhost:3306/spring?characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: root
  jpa:
    database: MYSQL
    show-sql: true
  info:
    head: head
    body: body
  management:
    endpoints:
      web:
        exposure:
          #加载所有的端点，默认只加载了info、health
          include: '*'
    endpoint:
      health:
        show-details: always
      #可以关闭指定的端点
      shutdown:
        enabled: false